version: 2.1
jobs:
  helm:
    docker:
      - image: eb129/docker-kubectl:3
    steps:
      - checkout
      - run: scripts/helm.sh
workflows:
  version: 2
  main:
    jobs:
      - helm:
          context: helm-charts-repository
