{{- if .Values.configMap.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "incident-bot.fullname" . }}-config
  labels:
    {{- include "incident-bot.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.configMap.data | indent 4 }}
{{- end }}
