{{- if and (.Values.database.enabled) (not (empty .Values.database.password)) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
          ports:
            - name: db
              containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512M
            requests:
              cpu: 250m
              memory: 256M
{{- end }}
